name: Bump verion
on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'formula name'
        required: true
      version:
        description: 'formula version'
        required: true
jobs:
  bump-formula-version:
    name: Bump Homebrew formula verion
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump formula
        run: gh workflow run bump-formula.yml --repo Alexander-Ignition/xc-gh --field formula=${{ github.event.inputs.formula }} --field version=${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
